const DUST_INFO = [
	{
		header: "Shielded",
		context:
			"DUST allows for transactions to take place without exposing metadata.",
	},
	{
		header: "Consumable",
		context:
			"DUST is consumed when used – meaning it is destroyed and does not cycle back into circulation.",
	},
	{
		header: "Renewable",
		context: "DUST is continually generated by NIGHT balances in perpetuity.",
	},
	{
		header: "Decaying",
		context:
			"A DUST balance decays when disassociated from the NIGHT address that generates it, meaning it cannot act as a store of value.",
	},
	{
		header: "Non-transferrable",
		context:
			"DUST cannot be transferred between addresses – insulating it from volatility and strengthening its sole utility.",
	},
];

export default DUST_INFO;
